"""Game constantes"""

DEFAULT_SCREEN_SIZE = (1280, 720)
DEFAULT_PLATEAU_SIZE = (1000, 720)
DEFAULT_RESOLUTION = 4
DEFAULT_DRAW_STEP = 1
DEFAULT_STEP_NUMBER = None

"""Button constantes"""

BUTTON_SIZE = (100, 50)
